# Generated by Django 4.0.7 on 2024-01-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=200, verbose_name='ایمیل')),
                ('mobile', models.CharField(max_length=11, verbose_name='تلفن همراه')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ثبت پیام')),
                ('subject', models.CharField(max_length=200, verbose_name='موضوع پیام')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('response', models.TextField(verbose_name='متن پاسخ مدیر')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
            ],
            options={
                'verbose_name': 'تماس با ما',
                'verbose_name_plural': 'لیست تماس با ما',
            },
        ),
    ]
