# Generated by Django 4.0.7 on 2024-01-13 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLinkTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان لینک فوتر')),
            ],
            options={
                'verbose_name': 'عنوان لینک فوتر',
                'verbose_name_plural': 'عناوین لینکهای فوتر',
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='عنوان سایت')),
                ('logo', models.ImageField(upload_to='site_setting', verbose_name='بارگزاری لوگو')),
                ('phone', models.CharField(max_length=11, verbose_name='تلفن فروشگاه')),
                ('fax', models.CharField(max_length=200, verbose_name='فکس فروشگاه')),
                ('address', models.CharField(max_length=200, verbose_name='آدرس')),
                ('email', models.CharField(max_length=200, verbose_name='ایمیل')),
                ('short_description', models.CharField(db_index=True, max_length=200, verbose_name='توضیحات کوتاه')),
                ('description', models.CharField(db_index=True, max_length=200, verbose_name='توضیحات کلی')),
                ('copyright_text', models.CharField(db_index=True, max_length=200, verbose_name='متن کپی رایت')),
                ('map_api', models.CharField(max_length=500, verbose_name='API نقشه')),
                ('facebook_url', models.URLField(max_length=500, verbose_name='فیسبوک')),
                ('aparat_url', models.URLField(max_length=500, verbose_name='آپارات')),
                ('instagram_url', models.URLField(max_length=500, verbose_name='اینستاگرام')),
                ('telegram_url', models.URLField(max_length=500, verbose_name='تلگرام')),
                ('youtube_url', models.URLField(max_length=500, verbose_name='یوتیوب')),
                ('main_setting', models.BooleanField(verbose_name='تنظیمات اصلی')),
            ],
            options={
                'verbose_name': 'تنظیمات',
                'verbose_name_plural': 'لیست تنظیمات',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_text', models.CharField(max_length=25, verbose_name='متن پیشنهاد ویژه روی اسلاید')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان اصلی اسلاید')),
                ('url_slide', models.URLField(max_length=500, verbose_name='لینک اسلاید')),
                ('sub_title', models.CharField(max_length=50, verbose_name='زیر عنوان اسلاید')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='قیمت')),
                ('delete_price', models.IntegerField(blank=True, null=True, verbose_name='قیمت با تخفیف')),
                ('button_text', models.CharField(max_length=50, verbose_name='متن دکمه')),
                ('button_url', models.URLField(max_length=500, verbose_name='url دکمه')),
                ('image', models.ImageField(upload_to='slider', verbose_name='بارگزاری اسلاید')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'اسلاید',
                'verbose_name_plural': 'اسلایدها',
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='لینک فوتر')),
                ('url_title', models.URLField(max_length=500, verbose_name='آدرس url لینک')),
                ('footer_link_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.footerlinktitle', verbose_name='عنوان سردسته لینک')),
            ],
            options={
                'verbose_name': 'لینک فوتر',
                'verbose_name_plural': 'لینکهای فوتر',
            },
        ),
    ]
